# golangci-lint configuration for production-ready code quality
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*_test.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
    enable-all: true
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  lll:
    line-length: 120
  
  goimports:
    local-prefixes: github.com/rajasatyajit/go-wc
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - dupImport
  
  funlen:
    lines: 100
    statements: 50
  
  gocognit:
    min-complexity: 20
  
  nestif:
    min-complexity: 4
  
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  
  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK
  
  whitespace:
    multi-if: false
    multi-func: false

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Additional quality linters
    - asciicheck
    - bodyclose
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wsl

  disable:
    - cyclop      # Duplicate of gocyclo
    - funlen      # Can be too restrictive for some cases
    - gocognit    # Duplicate of gocyclo
    - godot       # Not always necessary
    - goerr113    # Can be too restrictive
    - golint      # Deprecated
    - interfacer  # Deprecated
    - maligned    # Deprecated
    - scopelint   # Deprecated

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - dupl
        - lll
        - gosec
    
    # Exclude magic number checks for common values
    - text: "Magic number: (0|1|2|8|10|16|32|64|100|256|1024)"
      linters:
        - gomnd
    
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
    
    # Exclude lll issues for long lines with URLs or paths
    - linters:
        - lll
      source: "^//.*http[s]?://"
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0